<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="385748" started-at="2020-08-03T18:59:57Z" finished-at="2020-08-03T19:06:23Z">
    <groups>
    </groups>
    <test name="ChromeTest" duration-ms="385748" started-at="2020-08-03T18:59:57Z" finished-at="2020-08-03T19:06:23Z">
      <class name="BaseandTestClasses.TC2_AddCustomer">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@39ba5a14]" name="launchBrowser" is-config="true" duration-ms="13129" started-at="2020-08-04T00:34:43Z" finished-at="2020-08-04T00:34:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="TC2AddCustomer()[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@39ba5a14]" name="TC2AddCustomer" duration-ms="84091" started-at="2020-08-04T00:34:56Z" finished-at="2020-08-04T00:36:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC2_AddCustomer.TC2AddCustomer(TC2_AddCustomer.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2AddCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@39ba5a14]" name="tearDown" is-config="true" duration-ms="2150" started-at="2020-08-04T00:36:21Z" finished-at="2020-08-04T00:36:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC2_AddCustomer -->
      <class name="BaseandTestClasses.TC1_LoginLogout2">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@36d64342]" name="launchBrowser" is-config="true" duration-ms="17714" started-at="2020-08-04T00:32:34Z" finished-at="2020-08-04T00:32:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@36d64342]" name="TC1LoginLogout2" duration-ms="12303" started-at="2020-08-04T00:33:51Z" data-provider="datapro" finished-at="2020-08-04T00:34:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275222]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC1_LoginLogout2.TC1LoginLogout2(TC1_LoginLogout2.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="FAIL" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@36d64342]" name="TC1LoginLogout2" duration-ms="10309" started-at="2020-08-04T00:34:07Z" data-provider="datapro" finished-at="2020-08-04T00:34:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275223]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC1_LoginLogout2.TC1LoginLogout2(TC1_LoginLogout2.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="PASS" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@36d64342]" name="TC1LoginLogout2" duration-ms="23889" started-at="2020-08-04T00:34:18Z" data-provider="datapro" finished-at="2020-08-04T00:34:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275221]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@36d64342]" name="tearDown" is-config="true" duration-ms="1179" started-at="2020-08-04T00:34:42Z" finished-at="2020-08-04T00:34:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC1_LoginLogout2 -->
      <class name="BaseandTestClasses.TC1_LoginLogout1">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7f63425a]" name="launchBrowser" is-config="true" duration-ms="75235" started-at="2020-08-04T00:29:58Z" finished-at="2020-08-04T00:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="TC1LoginLogout1()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7f63425a]" name="TC1LoginLogout1" duration-ms="77136" started-at="2020-08-04T00:31:14Z" finished-at="2020-08-04T00:32:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7f63425a]" name="tearDown" is-config="true" duration-ms="2840" started-at="2020-08-04T00:32:31Z" finished-at="2020-08-04T00:32:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC1_LoginLogout1 -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
