<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="193948" started-at="2020-08-06T17:20:35Z" finished-at="2020-08-06T17:23:49Z">
    <groups>
    </groups>
    <test name="ChromeTest" duration-ms="193948" started-at="2020-08-06T17:20:35Z" finished-at="2020-08-06T17:23:49Z">
      <class name="BaseandTestClasses.TC1_LoginLogout2">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@49e4cb85]" name="launchBrowser" is-config="true" duration-ms="11866" started-at="2020-08-06T22:51:13Z" finished-at="2020-08-06T22:51:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@49e4cb85]" name="TC1LoginLogout2" duration-ms="17966" started-at="2020-08-06T22:51:28Z" data-provider="datapro" finished-at="2020-08-06T22:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275222]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC1_LoginLogout2.TC1LoginLogout2(TC1_LoginLogout2.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="FAIL" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@49e4cb85]" name="TC1LoginLogout2" duration-ms="8244" started-at="2020-08-06T22:51:47Z" data-provider="datapro" finished-at="2020-08-06T22:51:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275223]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC1_LoginLogout2.TC1LoginLogout2(TC1_LoginLogout2.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="PASS" signature="TC1LoginLogout2(java.lang.String, java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@49e4cb85]" name="TC1LoginLogout2" duration-ms="31310" started-at="2020-08-06T22:51:55Z" data-provider="datapro" finished-at="2020-08-06T22:52:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr275221]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AsuhAqa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout2@49e4cb85]" name="tearDown" is-config="true" duration-ms="1776" started-at="2020-08-06T22:52:27Z" finished-at="2020-08-06T22:52:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC1_LoginLogout2 -->
      <class name="BaseandTestClasses.TC2_AddCustomer">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@2133c8f8]" name="launchBrowser" is-config="true" duration-ms="23731" started-at="2020-08-06T22:52:28Z" finished-at="2020-08-06T22:52:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="TC2AddCustomer()[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@2133c8f8]" name="TC2AddCustomer" duration-ms="55193" started-at="2020-08-06T22:52:52Z" finished-at="2020-08-06T22:53:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at BaseandTestClasses.TC2_AddCustomer.TC2AddCustomer(TC2_AddCustomer.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2AddCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC2_AddCustomer@2133c8f8]" name="tearDown" is-config="true" duration-ms="1382" started-at="2020-08-06T22:53:48Z" finished-at="2020-08-06T22:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC2_AddCustomer -->
      <class name="BaseandTestClasses.TC1_LoginLogout1">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7c30a502]" name="launchBrowser" is-config="true" duration-ms="16123" started-at="2020-08-06T22:50:36Z" finished-at="2020-08-06T22:50:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="TC1LoginLogout1()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7c30a502]" name="TC1LoginLogout1" duration-ms="18894" started-at="2020-08-06T22:50:52Z" finished-at="2020-08-06T22:51:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1LoginLogout1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BaseandTestClasses.TC1_LoginLogout1@7c30a502]" name="tearDown" is-config="true" duration-ms="1772" started-at="2020-08-06T22:51:11Z" finished-at="2020-08-06T22:51:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BaseandTestClasses.TC1_LoginLogout1 -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
